genie:
  synapses_id: 'syn36709873'
  data_path: 'data/genie_v13.3/'
  case_list_folder: 'case_list'
  gene_panels_folder: 'gene_panels'
  processed_data: 'data/genie_processed/'
  dataset_path: 'data/'
  models_path: 'models/'
  training_mode: 'binary_classification'
  nlp_path: 'nlp/'
  nlp_thresholds_importance: 0.005
  bert_min_topic_size: 3
  categorical_features: ['PRIMARY_RACE']
  targets: ['Adrenal Gland Cancer',
            'Bladder Cancer',
            'Breast Cancer',
            'Cancer of Unknown Primary',
            'CNS Cancer',
            'CNS/Brain Cancer',
            'Colorectal Cancer',
            'Endometrial Cancer',
            'Glioma',
            'Head and Neck Cancer',
            'Gastrointestinal Stromal Tumor',
            'Infantile Fibrosarcoma',
            'Leukemia',
            'Melanoma',
            'Mesothelioma',
            'Nerve Sheath Tumor',
            'Non-Small Cell Lung Cancer',
            'Pancreatic Cancer',
            'Pineal Tumor',
            'Peripheral Nervous System',
            'Renal Cell Carcinoma',
            'Salivary Gland Cancer',
            'Skin Cancer',
            'Skin Cancer, Non-Melanoma',
            'Small Bowel Cancer',
            'UNKNOWN',
            'Wilms Tumor']
  files:
    clinical_patient:
      file_name: 'data_clinical_patient_13.3-consortium.txt'
      skip_rows: 4
    clinical_sample:
      file_name: 'data_clinical_sample_13.3-consortium.txt'
      skip_rows: 4
    cna:
      file_name: 'data_cna_13.3-consortium.txt'
    gene_matrix:
      file_name: 'data_gene_matrix_13.3-consortium.txt'
    mutations_extended:
      file_name: 'data_mutations_extended_13.3-consortium.txt'
  processed_files:
    clinical_patient:
      file_name: 'clinical_patient.csv'
    clinical_sample:
      file_name: 'clinical_sample.csv'
    patient_cancer_types:
      file_name: 'patient_cancer_types.csv'
    mutations_extended:
      file_name: 'mutations_extended.csv'
    gene_info:
      file_name: 'gene_info.csv'