genie:
  synapses_id: 'syn36709873'
  data_path: 'data/genie_v13.3/'
  case_list_folder: 'case_list'
  gene_panels_folder: 'gene_panels'
  processed_data: 'data/genie_processed/'
  dataset_path: 'data/'
  files:
    clinical_patient:
      file_name: 'data_clinical_patient_13.3-consortium.txt'
      skip_rows: 4
    clinical_sample:
      file_name: 'data_clinical_sample_13.3-consortium.txt'
      skip_rows: 4
    cna:
      file_name: 'data_cna_13.3-consortium.txt'
    gene_matrix:
      file_name: 'data_gene_matrix_13.3-consortium.txt'
    mutations_extended:
      file_name: 'data_mutations_extended_13.3-consortium.txt'
  processed_files:
    clinical_patient:
      file_name: 'clinical_patient.csv'
    clinical_sample:
      file_name: 'clinical_sample.csv'
    mutations_extended:
      file_name: 'mutations_processed.csv'