genie:
  synapses_id: 'syn36709873'
  data_path: 'data/genie_v13.3/'
  case_list_folder: 'case_list'
  gene_panels_folder: 'gene_panels'
  processed_data: 'data/genie_processed/'
  dataset_path: 'data/'
  models_path: 'models/'
  training_mode: 'binary_classification'
  aggregation_level: 'sample' # patient or sample
  nlp_path: 'nlp/'
  max_display_shap_importance: [10, 25, 100]
  gene_mutations_thresholds_importance: 0.01
  gene_mutations_shap_dependence: ['NF1_DEL',
                                   'NF1_SNP',
                                   'NF1_INS',
                                   'NF2_DEL',
                                   'NF2_SNP',
                                   'NF2_INS',
                                   'SMARCB1_DEL',
                                   'SMARCB1_SNP',
                                   'SMARCB1_INS',
                                   'LZTR1_DEL',
                                   'LZTR1_SNP',
                                   'LZTR1_INS']
  nlp_thresholds_importance: 0.001
  bert_min_topic_size: 3
  categorical_features: ['PRIMARY_RACE']
  clinical_features: ['AGE_CONTACT']
  targets: ['NF1_DEL',
            'NF1_SNP',
            'NF1_INS',
            'NF2_DEL',
            'NF2_SNP',
            'NF2_INS',
            'SMARCB1_DEL',
            'SMARCB1_SNP',
            'SMARCB1_INS',
            'LZTR1_DEL',
            'LZTR1_SNP',
            'LZTR1_INS',
            'Bladder Cancer',
            'Breast Cancer',
            'Cancer of Unknown Primary',
            'CNS Cancer',
            'Colorectal Cancer',
            'Endometrial Cancer',
            'Glioma',
            'Head and Neck Cancer',
            'Gastrointestinal Stromal Tumor',
            'Leukemia',
            'Melanoma',
            'Mesothelioma',
            'Nerve Sheath Tumor',
            'Non-Small Cell Lung Cancer',
            'Pancreatic Cancer',
            'Peripheral Nervous System',
            'Renal Cell Carcinoma',
            'Salivary Gland Cancer',
            'Skin Cancer, Non-Melanoma',
            'Small Bowel Cancer',
            'UNKNOWN']
  files:
    clinical_patient:
      file_name: 'data_clinical_patient_13.3-consortium.txt'
      skip_rows: 4
    clinical_sample:
      file_name: 'data_clinical_sample_13.3-consortium.txt'
      skip_rows: 4
    cna:
      file_name: 'data_cna_13.3-consortium.txt'
    gene_matrix:
      file_name: 'data_gene_matrix_13.3-consortium.txt'
    mutations_extended:
      file_name: 'data_mutations_extended_13.3-consortium.txt'
  processed_files:
    clinical_patient:
      file_name: 'clinical_patient.csv'
    clinical_sample:
      file_name: 'clinical_sample.csv'
    patient_cancer_types:
      file_name: 'patient_cancer_types.csv'
    sample_cancer_types:
      file_name: 'sample_cancer_types.csv'
    mutations_extended:
      file_name: 'mutations_extended.csv'
    gene_info:
      file_name: 'gene_info.csv'